import { WifiIcon, DeviceTabletIcon, BookOpenIcon } from '@heroicons/react/24/outline';

export interface FilterData {
  id: string;
  name: string;
  explanation: string;
  options: FilterOption[];
}

export interface FilterOption {
  value: string;
  label: string;
  checked: boolean;
  type: string;
  icon?: React.ElementType; // Add icon field to the FilterOption interface
}

export const typeFilterData: FilterData = {
  id: 'type',
  name: 'Primary_Filter',
  explanation: 'Select one or more counties to see resources available in those areas.',
  options: [
    {
      value: 'Find Digital Skills Help and Classes',
      label: 'Find Digital Skills Help and Classes',
      checked: false,
      type: 'Primary_Filter',
      icon: BookOpenIcon,
    },
    {
      value: 'Get a computer or device',
      label: 'Get a computer or device',
      checked: false,
      type: 'Primary_Filter',
      icon: DeviceTabletIcon,
    },
    {
      value: 'Find a public computer or Wi-Fi',
      label: 'Find a public computer or Wi-Fi',
      checked: false,
      type: 'Primary_Filter',
      icon: WifiIcon,
    },
  ],
};

export const geographyFilterData: FilterData = {
  id: 'geography',
  name: 'County',
  explanation: 'Select one or more counties to see resources available in those areas.',
  options: [
    {
      value: 'Alamance',
      label: 'Alamance',
      checked: false,
      type: 'County',
    },
    {
      value: 'Alexander',
      label: 'Alexander',
      checked: false,
      type: 'County',
    },
    {
      value: 'Alleghany',
      label: 'Alleghany',
      checked: false,
      type: 'County',
    },
    {
      value: 'Anson',
      label: 'Anson',
      checked: false,
      type: 'County',
    },
    {
      value: 'Ashe',
      label: 'Ashe',
      checked: false,
      type: 'County',
    },
    {
      value: 'Avery',
      label: 'Avery',
      checked: false,
      type: 'County',
    },
    {
      value: 'Beaufort',
      label: 'Beaufort',
      checked: false,
      type: 'County',
    },
    {
      value: 'Bertie',
      label: 'Bertie',
      checked: false,
      type: 'County',
    },
    {
      value: 'Bladen',
      label: 'Bladen',
      checked: false,
      type: 'County',
    },
    {
      value: 'Brunswick',
      label: 'Brunswick',
      checked: false,
      type: 'County',
    },
    {
      value: 'Buncombe',
      label: 'Buncombe',
      checked: false,
      type: 'County',
    },
    {
      value: 'Burke',
      label: 'Burke',
      checked: false,
      type: 'County',
    },
    {
      value: 'Cabarrus',
      label: 'Cabarrus',
      checked: false,
      type: 'County',
    },
    {
      value: 'Caldwell',
      label: 'Caldwell',
      checked: false,
      type: 'County',
    },
    {
      value: 'Camden',
      label: 'Camden',
      checked: false,
      type: 'County',
    },
    {
      value: 'Carteret',
      label: 'Carteret',
      checked: false,
      type: 'County',
    },
    {
      value: 'Caswell',
      label: 'Caswell',
      checked: false,
      type: 'County',
    },
    {
      value: 'Catawba',
      label: 'Catawba',
      checked: false,
      type: 'County',
    },
    {
      value: 'Chatham',
      label: 'Chatham',
      checked: false,
      type: 'County',
    },
    {
      value: 'Cherokee',
      label: 'Cherokee',
      checked: false,
      type: 'County',
    },
    {
      value: 'Chowan',
      label: 'Chowan',
      checked: false,
      type: 'County',
    },
    {
      value: 'Clay',
      label: 'Clay',
      checked: false,
      type: 'County',
    },
    {
      value: 'Cleveland',
      label: 'Cleveland',
      checked: false,
      type: 'County',
    },
    {
      value: 'Columbus',
      label: 'Columbus',
      checked: false,
      type: 'County',
    },
    {
      value: 'Craven',
      label: 'Craven',
      checked: false,
      type: 'County',
    },
    {
      value: 'Cumberland',
      label: 'Cumberland',
      checked: false,
      type: 'County',
    },
    {
      value: 'Currituck',
      label: 'Currituck',
      checked: false,
      type: 'County',
    },
    {
      value: 'Dare',
      label: 'Dare',
      checked: false,
      type: 'County',
    },
    {
      value: 'Davidson',
      label: 'Davidson',
      checked: false,
      type: 'County',
    },
    {
      value: 'Davie',
      label: 'Davie',
      checked: false,
      type: 'County',
    },
    {
      value: 'Duplin',
      label: 'Duplin',
      checked: false,
      type: 'County',
    },
    {
      value: 'Durham',
      label: 'Durham',
      checked: false,
      type: 'County',
    },
    {
      value: 'Edgecombe',
      label: 'Edgecombe',
      checked: false,
      type: 'County',
    },
    {
      value: 'Forsyth',
      label: 'Forsyth',
      checked: false,
      type: 'County',
    },
    {
      value: 'Franklin',
      label: 'Franklin',
      checked: false,
      type: 'County',
    },
    {
      value: 'Gaston',
      label: 'Gaston',
      checked: false,
      type: 'County',
    },
    {
      value: 'Gates',
      label: 'Gates',
      checked: false,
      type: 'County',
    },
    {
      value: 'Graham',
      label: 'Graham',
      checked: false,
      type: 'County',
    },
    {
      value: 'Granville',
      label: 'Granville',
      checked: false,
      type: 'County',
    },
    {
      value: 'Greene',
      label: 'Greene',
      checked: false,
      type: 'County',
    },
    {
      value: 'Guilford',
      label: 'Guilford',
      checked: false,
      type: 'County',
    },
    {
      value: 'Halifax',
      label: 'Halifax',
      checked: false,
      type: 'County',
    },
    {
      value: 'Harnett',
      label: 'Harnett',
      checked: false,
      type: 'County',
    },
    {
      value: 'Haywood',
      label: 'Haywood',
      checked: false,
      type: 'County',
    },
    {
      value: 'Henderson',
      label: 'Henderson',
      checked: false,
      type: 'County',
    },
    {
      value: 'Hertford',
      label: 'Hertford',
      checked: false,
      type: 'County',
    },
    {
      value: 'Hoke',
      label: 'Hoke',
      checked: false,
      type: 'County',
    },
    {
      value: 'Hyde',
      label: 'Hyde',
      checked: false,
      type: 'County',
    },
    {
      value: 'Iredell',
      label: 'Iredell',
      checked: false,
      type: 'County',
    },
    {
      value: 'Jackson',
      label: 'Jackson',
      checked: false,
      type: 'County',
    },
    {
      value: 'Johnston',
      label: 'Johnston',
      checked: false,
      type: 'County',
    },
    {
      value: 'Jones',
      label: 'Jones',
      checked: false,
      type: 'County',
    },
    {
      value: 'Lee',
      label: 'Lee',
      checked: false,
      type: 'County',
    },
    {
      value: 'Lenoir',
      label: 'Lenoir',
      checked: false,
      type: 'County',
    },
    {
      value: 'Lincoln',
      label: 'Lincoln',
      checked: false,
      type: 'County',
    },
    {
      value: 'Macon',
      label: 'Macon',
      checked: false,
      type: 'County',
    },
    {
      value: 'Madison',
      label: 'Madison',
      checked: false,
      type: 'County',
    },
    {
      value: 'Martin',
      label: 'Martin',
      checked: false,
      type: 'County',
    },
    {
      value: 'McDowell',
      label: 'McDowell',
      checked: false,
      type: 'County',
    },
    {
      value: 'Mecklenburg',
      label: 'Mecklenburg',
      checked: false,
      type: 'County',
    },
    {
      value: 'Mitchell',
      label: 'Mitchell',
      checked: false,
      type: 'County',
    },
    {
      value: 'Montgomery',
      label: 'Montgomery',
      checked: false,
      type: 'County',
    },
    {
      value: 'Moore',
      label: 'Moore',
      checked: false,
      type: 'County',
    },
    {
      value: 'Nash',
      label: 'Nash',
      checked: false,
      type: 'County',
    },
    {
      value: 'New Hanover',
      label: 'New Hanover',
      checked: false,
      type: 'County',
    },
    {
      value: 'Northampton',
      label: 'Northampton',
      checked: false,
      type: 'County',
    },
    {
      value: 'Onslow',
      label: 'Onslow',
      checked: false,
      type: 'County',
    },
    {
      value: 'Orange',
      label: 'Orange',
      checked: false,
      type: 'County',
    },
    {
      value: 'Pamlico',
      label: 'Pamlico',
      checked: false,
      type: 'County',
    },
    {
      value: 'Pasquotank',
      label: 'Pasquotank',
      checked: false,
      type: 'County',
    },
    {
      value: 'Pender',
      label: 'Pender',
      checked: false,
      type: 'County',
    },
    {
      value: 'Perquimans',
      label: 'Perquimans',
      checked: false,
      type: 'County',
    },
    {
      value: 'Person',
      label: 'Person',
      checked: false,
      type: 'County',
    },
    {
      value: 'Pitt',
      label: 'Pitt',
      checked: false,
      type: 'County',
    },
    {
      value: 'Polk',
      label: 'Polk',
      checked: false,
      type: 'County',
    },
    {
      value: 'Randolph',
      label: 'Randolph',
      checked: false,
      type: 'County',
    },
    {
      value: 'Richmond',
      label: 'Richmond',
      checked: false,
      type: 'County',
    },
    {
      value: 'Robeson',
      label: 'Robeson',
      checked: false,
      type: 'County',
    },
    {
      value: 'Rockingham',
      label: 'Rockingham',
      checked: false,
      type: 'County',
    },
    {
      value: 'Rowan',
      label: 'Rowan',
      checked: false,
      type: 'County',
    },
    {
      value: 'Rutherford',
      label: 'Rutherford',
      checked: false,
      type: 'County',
    },
    {
      value: 'Sampson',
      label: 'Sampson',
      checked: false,
      type: 'County',
    },
    {
      value: 'Scotland',
      label: 'Scotland',
      checked: false,
      type: 'County',
    },
    {
      value: 'Stanly',
      label: 'Stanly',
      checked: false,
      type: 'County',
    },
    {
      value: 'Stokes',
      label: 'Stokes',
      checked: false,
      type: 'County',
    },
    {
      value: 'Surry',
      label: 'Surry',
      checked: false,
      type: 'County',
    },
    {
      value: 'Swain',
      label: 'Swain',
      checked: false,
      type: 'County',
    },
    {
      value: 'Transylvania',
      label: 'Transylvania',
      checked: false,
      type: 'County',
    },
    {
      value: 'Tyrrell',
      label: 'Tyrrell',
      checked: false,
      type: 'County',
    },
    {
      value: 'Union',
      label: 'Union',
      checked: false,
      type: 'County',
    },
    {
      value: 'Vance',
      label: 'Vance',
      checked: false,
      type: 'County',
    },
    {
      value: 'Wake',
      label: 'Wake',
      checked: false,
      type: 'County',
    },
    {
      value: 'Warren',
      label: 'Warren',
      checked: false,
      type: 'County',
    },
    {
      value: 'Washington',
      label: 'Washington',
      checked: false,
      type: 'County',
    },
    {
      value: 'Watauga',
      label: 'Watauga',
      checked: false,
      type: 'County',
    },
    {
      value: 'Wayne',
      label: 'Wayne',
      checked: false,
      type: 'County',
    },
    {
      value: 'Wilkes',
      label: 'Wilkes',
      checked: false,
      type: 'County',
    },
    {
      value: 'Wilson',
      label: 'Wilson',
      checked: false,
      type: 'County',
    },
    {
      value: 'Yadkin',
      label: 'Yadkin',
      checked: false,
      type: 'County',
    },
    {
      value: 'Yancey',
      label: 'Yancey',
      checked: false,
      type: 'County',
    },
    {
      value: '28619',
      label: '28619',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27559',
      label: '27559',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27881',
      label: '27881',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27843',
      label: '27843',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27244',
      label: '27244',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27203',
      label: '27203',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27298',
      label: '27298',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27235',
      label: '27235',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28054',
      label: '28054',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28611',
      label: '28611',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27208',
      label: '27208',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28098',
      label: '28098',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27249',
      label: '27249',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27609',
      label: '27609',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28135',
      label: '28135',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28447',
      label: '28447',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27820',
      label: '27820',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28771',
      label: '28771',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27939',
      label: '27939',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28349',
      label: '28349',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28453',
      label: '28453',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27885',
      label: '27885',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28745',
      label: '28745',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27860',
      label: '27860',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27919',
      label: '27919',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27946',
      label: '27946',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27853',
      label: '27853',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27956',
      label: '27956',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28742',
      label: '28742',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27870',
      label: '27870',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27024',
      label: '27024',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28758',
      label: '28758',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28129',
      label: '28129',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27522',
      label: '27522',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27017',
      label: '27017',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28128',
      label: '28128',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28726',
      label: '28726',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28719',
      label: '28719',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28789',
      label: '28789',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28455',
      label: '28455',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28683',
      label: '28683',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27970',
      label: '27970',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27025',
      label: '27025',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27042',
      label: '27042',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27014',
      label: '27014',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28325',
      label: '28325',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28323',
      label: '28323',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27357',
      label: '27357',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28033',
      label: '28033',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28637',
      label: '28637',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28667',
      label: '28667',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27562',
      label: '27562',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27502',
      label: '27502',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28436',
      label: '28436',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27310',
      label: '27310',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27409',
      label: '27409',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27233',
      label: '27233',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27263',
      label: '27263',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28012',
      label: '28012',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28606',
      label: '28606',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28052',
      label: '28052',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27605',
      label: '27605',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27054',
      label: '27054',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27606',
      label: '27606',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27408',
      label: '27408',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28452',
      label: '28452',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27574',
      label: '27574',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28562',
      label: '28562',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28733',
      label: '28733',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28684',
      label: '28684',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28464',
      label: '28464',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27927',
      label: '27927',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27923',
      label: '27923',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27966',
      label: '27966',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28119',
      label: '28119',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27875',
      label: '27875',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28791',
      label: '28791',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27932',
      label: '27932',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28646',
      label: '28646',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27890',
      label: '27890',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28777',
      label: '28777',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28616',
      label: '28616',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28327',
      label: '28327',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28909',
      label: '28909',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27924',
      label: '27924',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28668',
      label: '28668',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28740',
      label: '28740',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28073',
      label: '28073',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27925',
      label: '27925',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27967',
      label: '27967',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28712',
      label: '28712',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28746',
      label: '28746',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27872',
      label: '27872',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28364',
      label: '28364',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28749',
      label: '28749',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27281',
      label: '27281',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28755',
      label: '28755',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28358',
      label: '28358',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28772',
      label: '28772',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28328',
      label: '28328',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28762',
      label: '28762',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28553',
      label: '28553',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28577',
      label: '28577',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28640',
      label: '28640',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28557',
      label: '28557',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27981',
      label: '27981',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27936',
      label: '27936',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27587',
      label: '27587',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27508',
      label: '27508',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28125',
      label: '28125',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28422',
      label: '28422',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28451',
      label: '28451',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27517',
      label: '27517',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28107',
      label: '28107',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28027',
      label: '28027',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27613',
      label: '27613',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27513',
      label: '27513',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27055',
      label: '27055',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27601',
      label: '27601',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27358',
      label: '27358',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27893',
      label: '27893',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27704',
      label: '27704',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27863',
      label: '27863',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28547',
      label: '28547',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28551',
      label: '28551',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28542',
      label: '28542',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27803',
      label: '27803',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28212',
      label: '28212',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27503',
      label: '27503',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27807',
      label: '27807',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28348',
      label: '28348',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27051',
      label: '27051',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28226',
      label: '28226',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28701',
      label: '28701',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28770',
      label: '28770',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28214',
      label: '28214',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28278',
      label: '28278',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28078',
      label: '28078',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27856',
      label: '27856',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28580',
      label: '28580',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28037',
      label: '28037',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28412',
      label: '28412',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27053',
      label: '27053',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27521',
      label: '27521',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28398',
      label: '28398',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28368',
      label: '28368',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27506',
      label: '27506',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27239',
      label: '27239',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28086',
      label: '28086',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28645',
      label: '28645',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28612',
      label: '28612',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28420',
      label: '28420',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27407',
      label: '27407',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28449',
      label: '28449',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28480',
      label: '28480',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27529',
      label: '27529',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28147',
      label: '28147',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27048',
      label: '27048',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27568',
      label: '27568',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28041',
      label: '28041',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27268',
      label: '27268',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28716',
      label: '28716',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28443',
      label: '28443',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28585',
      label: '28585',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27291',
      label: '27291',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28743',
      label: '28743',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27941',
      label: '27941',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27897',
      label: '27897',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28739',
      label: '28739',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27806',
      label: '27806',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28472',
      label: '28472',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27212',
      label: '27212',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27379',
      label: '27379',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28906',
      label: '28906',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28109',
      label: '28109',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27839',
      label: '27839',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27817',
      label: '27817',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28621',
      label: '28621',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28766',
      label: '28766',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28623',
      label: '28623',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28705',
      label: '28705',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28652',
      label: '28652',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28315',
      label: '28315',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28736',
      label: '28736',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28707',
      label: '28707',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28337',
      label: '28337',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28020',
      label: '28020',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28394',
      label: '28394',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27974',
      label: '27974',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28373',
      label: '28373',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28768',
      label: '28768',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28167',
      label: '28167',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28018',
      label: '28018',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27247',
      label: '27247',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27957',
      label: '27957',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28644',
      label: '28644',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28017',
      label: '28017',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28718',
      label: '28718',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28654',
      label: '28654',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28375',
      label: '28375',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28626',
      label: '28626',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28528',
      label: '28528',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28367',
      label: '28367',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27582',
      label: '27582',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28363',
      label: '28363',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27954',
      label: '27954',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27968',
      label: '27968',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27943',
      label: '27943',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27861',
      label: '27861',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28077',
      label: '28077',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28343',
      label: '28343',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27295',
      label: '27295',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28625',
      label: '28625',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27545',
      label: '27545',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27265',
      label: '27265',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28678',
      label: '28678',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28479',
      label: '28479',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27253',
      label: '27253',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28104',
      label: '28104',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28761',
      label: '28761',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28642',
      label: '28642',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27617',
      label: '27617',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27519',
      label: '27519',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28203',
      label: '28203',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27830',
      label: '27830',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28574',
      label: '28574',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28546',
      label: '28546',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28206',
      label: '28206',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28333',
      label: '28333',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28513',
      label: '28513',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28312',
      label: '28312',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27837',
      label: '27837',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27878',
      label: '27878',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27829',
      label: '27829',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27708',
      label: '27708',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28715',
      label: '28715',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28395',
      label: '28395',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27050',
      label: '27050',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27886',
      label: '27886',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27572',
      label: '27572',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28753',
      label: '28753',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27009',
      label: '27009',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28216',
      label: '28216',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28031',
      label: '28031',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28401',
      label: '28401',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28504',
      label: '28504',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28609',
      label: '28609',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27549',
      label: '27549',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27292',
      label: '27292',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27801',
      label: '27801',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28110',
      label: '28110',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27011',
      label: '27011',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27607',
      label: '27607',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27713',
      label: '27713',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27518',
      label: '27518',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28071',
      label: '28071',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28202',
      label: '28202',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27883',
      label: '27883',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28540',
      label: '28540',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27569',
      label: '27569',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27260',
      label: '27260',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28578',
      label: '28578',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28590',
      label: '28590',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28305',
      label: '28305',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27879',
      label: '27879',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28314',
      label: '28314',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27812',
      label: '27812',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28344',
      label: '28344',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28759',
      label: '28759',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27021',
      label: '27021',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28310',
      label: '28310',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28356',
      label: '28356',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28269',
      label: '28269',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27406',
      label: '27406',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28658',
      label: '28658',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28405',
      label: '28405',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27541',
      label: '27541',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27016',
      label: '27016',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27030',
      label: '27030',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28341',
      label: '28341',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27370',
      label: '27370',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28112',
      label: '28112',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28127',
      label: '28127',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28671',
      label: '28671',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28034',
      label: '28034',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27282',
      label: '27282',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28428',
      label: '28428',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27313',
      label: '27313',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27577',
      label: '27577',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28366',
      label: '28366',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27326',
      label: '27326',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28144',
      label: '28144',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28137',
      label: '28137',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27608',
      label: '27608',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27027',
      label: '27027',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28088',
      label: '28088',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27342',
      label: '27342',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28170',
      label: '28170',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28692',
      label: '28692',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28782',
      label: '28782',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28091',
      label: '28091',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28573',
      label: '28573',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27965',
      label: '27965',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27810',
      label: '27810',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27804',
      label: '27804',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28650',
      label: '28650',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27028',
      label: '27028',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28508',
      label: '28508',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28090',
      label: '28090',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28638',
      label: '28638',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27350',
      label: '27350',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28469',
      label: '28469',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28409',
      label: '28409',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27455',
      label: '27455',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27599',
      label: '27599',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27248',
      label: '27248',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27341',
      label: '27341',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27325',
      label: '27325',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28023',
      label: '28023',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27697',
      label: '27697',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27695',
      label: '27695',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28478',
      label: '28478',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27842',
      label: '27842',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27343',
      label: '27343',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27958',
      label: '27958',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28393',
      label: '28393',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27876',
      label: '27876',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28618',
      label: '28618',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27824',
      label: '27824',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28773',
      label: '28773',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27007',
      label: '27007',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28731',
      label: '28731',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27615',
      label: '27615',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28790',
      label: '28790',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28713',
      label: '28713',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28430',
      label: '28430',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28150',
      label: '28150',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28552',
      label: '28552',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27922',
      label: '27922',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27563',
      label: '27563',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27921',
      label: '27921',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27356',
      label: '27356',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28631',
      label: '28631',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28509',
      label: '28509',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27209',
      label: '27209',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28350',
      label: '28350',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28378',
      label: '28378',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27507',
      label: '27507',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27846',
      label: '27846',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28708',
      label: '28708',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28649',
      label: '28649',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28362',
      label: '28362',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28763',
      label: '28763',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28615',
      label: '28615',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28385',
      label: '28385',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28579',
      label: '28579',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28076',
      label: '28076',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28511',
      label: '28511',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28575',
      label: '28575',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28666',
      label: '28666',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27537',
      label: '27537',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27262',
      label: '27262',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27012',
      label: '27012',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28117',
      label: '28117',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28660',
      label: '28660',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28636',
      label: '28636',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27516',
      label: '27516',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28628',
      label: '28628',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27320',
      label: '27320',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28075',
      label: '28075',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27214',
      label: '27214',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27604',
      label: '27604',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27101',
      label: '27101',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27858',
      label: '27858',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28280',
      label: '28280',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28584',
      label: '28584',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27530',
      label: '27530',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28555',
      label: '28555',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27851',
      label: '27851',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27104',
      label: '27104',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27896',
      label: '27896',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27707',
      label: '27707',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28303',
      label: '28303',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27703',
      label: '27703',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27884',
      label: '27884',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27852',
      label: '27852',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28805',
      label: '28805',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27524',
      label: '27524',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27712',
      label: '27712',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28209',
      label: '28209',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28384',
      label: '28384',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28277',
      label: '28277',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27023',
      label: '27023',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28613',
      label: '28613',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27401',
      label: '27401',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27501',
      label: '27501',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27504',
      label: '27504',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27046',
      label: '27046',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27546',
      label: '27546',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27332',
      label: '27332',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28080',
      label: '28080',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27526',
      label: '27526',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27592',
      label: '27592',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27330',
      label: '27330',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28690',
      label: '28690',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27256',
      label: '27256',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28630',
      label: '28630',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28120',
      label: '28120',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28411',
      label: '28411',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27301',
      label: '27301',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27283',
      label: '27283',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28605',
      label: '28605',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28056',
      label: '28056',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27316',
      label: '27316',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28036',
      label: '28036',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28624',
      label: '28624',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28146',
      label: '28146',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27576',
      label: '27576',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27593',
      label: '27593',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28039',
      label: '28039',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27573',
      label: '27573',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27832',
      label: '27832',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28421',
      label: '28421',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28435',
      label: '28435',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28679',
      label: '28679',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27565',
      label: '27565',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27831',
      label: '27831',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28751',
      label: '28751',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28102',
      label: '28102',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27985',
      label: '27985',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27917',
      label: '27917',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28431',
      label: '28431',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28604',
      label: '28604',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28009',
      label: '28009',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28653',
      label: '28653',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27892',
      label: '27892',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28676',
      label: '28676',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28438',
      label: '28438',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28463',
      label: '28463',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28774',
      label: '28774',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28587',
      label: '28587',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28779',
      label: '28779',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27551',
      label: '27551',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28556',
      label: '28556',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27553',
      label: '27553',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27986',
      label: '27986',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28554',
      label: '28554',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27983',
      label: '27983',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27306',
      label: '27306',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28357',
      label: '28357',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28747',
      label: '28747',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28533',
      label: '28533',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28019',
      label: '28019',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27509',
      label: '27509',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28516',
      label: '28516',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27948',
      label: '27948',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27938',
      label: '27938',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27920',
      label: '27920',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27841',
      label: '27841',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28775',
      label: '28775',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27709',
      label: '27709',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27982',
      label: '27982',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28101',
      label: '28101',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27202',
      label: '27202',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28282',
      label: '28282',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28352',
      label: '28352',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27584',
      label: '27584',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27826',
      label: '27826',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27980',
      label: '27980',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28729',
      label: '28729',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28001',
      label: '28001',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27823',
      label: '27823',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27311',
      label: '27311',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28662',
      label: '28662',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28710',
      label: '28710',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27821',
      label: '27821',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27299',
      label: '27299',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28163',
      label: '28163',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27874',
      label: '27874',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28320',
      label: '28320',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28783',
      label: '28783',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28152',
      label: '28152',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28675',
      label: '28675',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28904',
      label: '28904',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28529',
      label: '28529',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27928',
      label: '27928',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28560',
      label: '28560',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28434',
      label: '28434',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28040',
      label: '28040',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27909',
      label: '27909',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28725',
      label: '28725',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28714',
      label: '28714',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28377',
      label: '28377',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28685',
      label: '28685',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28043',
      label: '28043',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28383',
      label: '28383',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28372',
      label: '28372',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28570',
      label: '28570',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28379',
      label: '28379',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28643',
      label: '28643',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28520',
      label: '28520',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28594',
      label: '28594',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28345',
      label: '28345',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27915',
      label: '27915',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27857',
      label: '27857',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27840',
      label: '27840',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27864',
      label: '27864',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28032',
      label: '28032',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27340',
      label: '27340',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27201',
      label: '27201',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27969',
      label: '27969',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28355',
      label: '28355',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27360',
      label: '27360',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27597',
      label: '27597',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27571',
      label: '27571',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27544',
      label: '27544',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28634',
      label: '28634',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27013',
      label: '27013',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28655',
      label: '28655',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27355',
      label: '27355',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28641',
      label: '28641',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28025',
      label: '28025',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28097',
      label: '28097',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28801',
      label: '28801',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28445',
      label: '28445',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28539',
      label: '28539',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28582',
      label: '28582',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27103',
      label: '27103',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28803',
      label: '28803',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27533',
      label: '27533',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27109',
      label: '27109',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27880',
      label: '27880',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27278',
      label: '27278',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27871',
      label: '27871',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28382',
      label: '28382',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28704',
      label: '28704',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28207',
      label: '28207',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28270',
      label: '28270',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27596',
      label: '27596',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27816',
      label: '27816',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27844',
      label: '27844',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27603',
      label: '27603',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27882',
      label: '27882',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27312',
      label: '27312',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27018',
      label: '27018',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28244',
      label: '28244',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28301',
      label: '28301',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28306',
      label: '28306',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28454',
      label: '28454',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28804',
      label: '28804',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28204',
      label: '28204',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28521',
      label: '28521',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27531',
      label: '27531',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28586',
      label: '28586',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28215',
      label: '28215',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27828',
      label: '27828',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27827',
      label: '27827',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28211',
      label: '28211',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28105',
      label: '28105',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28210',
      label: '28210',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28391',
      label: '28391',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28274',
      label: '28274',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28331',
      label: '28331',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27583',
      label: '27583',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28732',
      label: '28732',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27043',
      label: '27043',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28308',
      label: '28308',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28307',
      label: '28307',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28711',
      label: '28711',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28371',
      label: '28371',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27284',
      label: '27284',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28792',
      label: '28792',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28223',
      label: '28223',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28273',
      label: '28273',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28501',
      label: '28501',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28525',
      label: '28525',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28610',
      label: '28610',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27405',
      label: '27405',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27302',
      label: '27302',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28682',
      label: '28682',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27891',
      label: '27891',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27022',
      label: '27022',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28164',
      label: '28164',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27505',
      label: '27505',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27205',
      label: '27205',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27371',
      label: '27371',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28016',
      label: '28016',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28468',
      label: '28468',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28467',
      label: '28467',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27819',
      label: '27819',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28456',
      label: '28456',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27288',
      label: '27288',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27610',
      label: '27610',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27612',
      label: '27612',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28607',
      label: '28607',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28457',
      label: '28457',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28722',
      label: '28722',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27855',
      label: '27855',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27305',
      label: '27305',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27950',
      label: '27950',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28702',
      label: '28702',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27944',
      label: '27944',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27929',
      label: '27929',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27964',
      label: '27964',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28785',
      label: '28785',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28139',
      label: '28139',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27869',
      label: '27869',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27808',
      label: '27808',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28905',
      label: '28905',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28748',
      label: '28748',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28334',
      label: '28334',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27040',
      label: '27040',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28757',
      label: '28757',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28390',
      label: '28390',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28602',
      label: '28602',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28429',
      label: '28429',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28538',
      label: '28538',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28092',
      label: '28092',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27041',
      label: '27041',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28006',
      label: '28006',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28173',
      label: '28173',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28103',
      label: '28103',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27523',
      label: '27523',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27252',
      label: '27252',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28470',
      label: '28470',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28462',
      label: '28462',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27317',
      label: '27317',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28133',
      label: '28133',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27410',
      label: '27410',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28442',
      label: '28442',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28622',
      label: '28622',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28432',
      label: '28432',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28433',
      label: '28433',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27814',
      label: '27814',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28717',
      label: '28717',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28537',
      label: '28537',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27976',
      label: '27976',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27910',
      label: '27910',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27259',
      label: '27259',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28571',
      label: '28571',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27376',
      label: '27376',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27818',
      label: '27818',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28734',
      label: '28734',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27570',
      label: '27570',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28386',
      label: '28386',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27847',
      label: '27847',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28669',
      label: '28669',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28670',
      label: '28670',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27536',
      label: '27536',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28392',
      label: '28392',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28340',
      label: '28340',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28160',
      label: '28160',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28074',
      label: '28074',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28651',
      label: '28651',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28089',
      label: '28089',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27949',
      label: '27949',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28581',
      label: '28581',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28693',
      label: '28693',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28359',
      label: '28359',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28512',
      label: '28512',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28617',
      label: '28617',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27953',
      label: '27953',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28330',
      label: '28330',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27555',
      label: '27555',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27510',
      label: '27510',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27412',
      label: '27412',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27377',
      label: '27377',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27520',
      label: '27520',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28081',
      label: '28081',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27527',
      label: '27527',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28159',
      label: '28159',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28681',
      label: '28681',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28083',
      label: '28083',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28072',
      label: '28072',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28465',
      label: '28465',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27213',
      label: '27213',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28721',
      label: '28721',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28425',
      label: '28425',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27866',
      label: '27866',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27862',
      label: '27862',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28698',
      label: '28698',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28007',
      label: '28007',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28458',
      label: '28458',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27916',
      label: '27916',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28466',
      label: '28466',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28786',
      label: '28786',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27960',
      label: '27960',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27845',
      label: '27845',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27877',
      label: '27877',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27947',
      label: '27947',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28756',
      label: '28756',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27973',
      label: '27973',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28448',
      label: '28448',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28444',
      label: '28444',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27850',
      label: '27850',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28901',
      label: '28901',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28423',
      label: '28423',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27865',
      label: '27865',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28450',
      label: '28450',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27315',
      label: '27315',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27962',
      label: '27962',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28735',
      label: '28735',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27616',
      label: '27616',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27351',
      label: '27351',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28902',
      label: '28902',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27047',
      label: '27047',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28439',
      label: '28439',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28664',
      label: '28664',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28387',
      label: '28387',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28374',
      label: '28374',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28042',
      label: '28042',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28663',
      label: '28663',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28510',
      label: '28510',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28136',
      label: '28136',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28741',
      label: '28741',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27594',
      label: '27594',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28114',
      label: '28114',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27849',
      label: '27849',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28659',
      label: '28659',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28527',
      label: '28527',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27229',
      label: '27229',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28332',
      label: '28332',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28720',
      label: '28720',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27979',
      label: '27979',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28347',
      label: '28347',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28697',
      label: '28697',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28338',
      label: '28338',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27926',
      label: '27926',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27937',
      label: '27937',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28531',
      label: '28531',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28524',
      label: '28524',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27825',
      label: '27825',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27972',
      label: '27972',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28672',
      label: '28672',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28629',
      label: '28629',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27539',
      label: '27539',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27525',
      label: '27525',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27591',
      label: '27591',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27589',
      label: '27589',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27614',
      label: '27614',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28166',
      label: '28166',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27557',
      label: '27557',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28115',
      label: '28115',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28461',
      label: '28461',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27207',
      label: '27207',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28124',
      label: '28124',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27511',
      label: '27511',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27542',
      label: '27542',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28518',
      label: '28518',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27534',
      label: '27534',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27106',
      label: '27106',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28544',
      label: '28544',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28205',
      label: '28205',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28530',
      label: '28530',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28806',
      label: '28806',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27813',
      label: '27813',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27110',
      label: '27110',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28213',
      label: '28213',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28787',
      label: '28787',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28709',
      label: '28709',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27019',
      label: '27019',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27052',
      label: '27052',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27045',
      label: '27045',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28311',
      label: '28311',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28217',
      label: '28217',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28778',
      label: '28778',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28730',
      label: '28730',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28262',
      label: '28262',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28134',
      label: '28134',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27514',
      label: '27514',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27243',
      label: '27243',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27231',
      label: '27231',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27809',
      label: '27809',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27403',
      label: '27403',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27006',
      label: '27006',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27540',
      label: '27540',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27314',
      label: '27314',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28424',
      label: '28424',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28723',
      label: '28723',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28515',
      label: '28515',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27242',
      label: '27242',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27942',
      label: '27942',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28627',
      label: '28627',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28441',
      label: '28441',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27805',
      label: '27805',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28635',
      label: '28635',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28788',
      label: '28788',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28519',
      label: '28519',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28523',
      label: '28523',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28169',
      label: '28169',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27556',
      label: '27556',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28752',
      label: '28752',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28369',
      label: '28369',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28360',
      label: '28360',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28532',
      label: '28532',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27581',
      label: '27581',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28694',
      label: '28694',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28665',
      label: '28665',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28376',
      label: '28376',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27935',
      label: '27935',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28781',
      label: '28781',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28589',
      label: '28589',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28024',
      label: '28024',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27959',
      label: '27959',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27978',
      label: '27978',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28351',
      label: '28351',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28396',
      label: '28396',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27374',
      label: '27374',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27815',
      label: '27815',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28677',
      label: '28677',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27107',
      label: '27107',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27127',
      label: '27127',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28689',
      label: '28689',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27020',
      label: '27020',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28079',
      label: '28079',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27344',
      label: '27344',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27217',
      label: '27217',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27258',
      label: '27258',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28657',
      label: '28657',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27349',
      label: '27349',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28227',
      label: '28227',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28138',
      label: '28138',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27560',
      label: '27560',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27834',
      label: '27834',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27701',
      label: '27701',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27105',
      label: '27105',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27705',
      label: '27705',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28572',
      label: '28572',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28460',
      label: '28460',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28403',
      label: '28403',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28208',
      label: '28208',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28304',
      label: '28304',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28365',
      label: '28365',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28543',
      label: '28543',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27822',
      label: '27822',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27889',
      label: '27889',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27888',
      label: '27888',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27873',
      label: '27873',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28318',
      label: '28318',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28342',
      label: '28342',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28399',
      label: '28399',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28601',
      label: '28601',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27411',
      label: '27411',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28526',
      label: '28526',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28673',
      label: '28673',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28754',
      label: '28754',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28339',
      label: '28339',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28021',
      label: '28021',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28168',
      label: '28168',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28326',
      label: '28326',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '27215',
      label: '27215',
      checked: false,
      type: 'ZipCode',
    },
    {
      value: '28174',
      label: '28174',
      checked: false,
      type: 'ZipCode',
    },
  ],
};
